name: Build and Test

on:
  pull_request:
    types:
      - opened
    paths:
      - 'src/**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if-merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Tests
        run: cargo test