name: Build and Test

on:
  push:
    paths:
      - 'src/**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Release build
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: Release build
      uses: actions-rs/cargo@v1
      with:
        command: test