name: Publish and Release

on:
  pull_request:
    types:
      - closed
    branches: [ "main" ]
    paths:
      - 'src/**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if-merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
        args: --release
      - name: Publish to Cargo
        uses: actions-rs/cargo@v1
        with:
          command: publish